// Lumen desktop shell (Wails v2).
//
// PLACEHOLDER: this file is the Wails entrypoint. The Vite/React app at
// the repository root is the frontend; when the project is initialised
// as a Wails module, its built output is embedded here (frontend/dist).
// See docs/architecture.md §"Running under Wails".
package main

import (
	"embed"

	"github.com/wailsapp/wails/v2"
	"github.com/wailsapp/wails/v2/pkg/options"
	"github.com/wailsapp/wails/v2/pkg/options/assetserver"
)

//go:embed wails.json
var assetServerJSON embed.FS

//go:embed all:frontend/dist
var assets embed.FS

func main() {
	app := NewApp()

	err := wails.Run(&options.App{
		Title:     "Lumen — Research Browser & Reader",
		Width:     1440,
		Height:    900,
		MinWidth:  1024,
		MinHeight: 640,
		AssetServer: &assetserver.Options{
			Assets: assets,
		},
		BackgroundColour: &options.RGBA{R: 250, G: 248, B: 241, A: 1},
		OnStartup:        app.startup,
		OnShutdown:       app.shutdown,
		Bind: []interface{}{
			app,
			// Services are bound individually so the frontend can call
			// e.g. window.go.services.Filesystem.ShowContainingFolder.
			app.fs,
			app.storage,
			app.docs,
			app.ai,
		},
	})
	if err != nil {
		println("Error:", err.Error())
	}
}

// Keep the unused JSON asset reference from breaking builds before the
// wails.json file is generated by `wails init`.
var _ = assetServerJSON
