/**
 * Lumen mock data — realistic research content so every UI state is
 * demonstrable before real services are connected.
 *
 * Status: MOCK DATA. Shapes match the domain model exactly so this file
 * can be deleted once the Go backend + storage layer supply the same
 * structures (see docs/future-work.md §Replacing mock data).
 */

import type {
  AppState,
  BrowserSession,
  BrowserTab,
  Document,
  DocumentChange,
  AIActivity,
  FileTreeNode,
  Source,
} from "../types/domain";

/* ------------------------------------------------------------------ */
/* Sources                                                             */
/* ------------------------------------------------------------------ */

const sources: Record<string, Source> = {
  "src-a": {
    id: "src-a",
    kind: "pdf",
    title: "Chemiosmosis and ATP synthesis",
    origin: "research_papers/mitchell_1961.pdf",
    typeLabel: "PDF paper",
    abstract:
      "J. Mitchell's original account of chemiosmotic coupling: a proton gradient, generated by electron transport, drives ATP synthesis through ATP synthase.",
    saved: true,
    inReader: true,
    documentId: "doc-a",
  },
  "src-b": {
    id: "src-b",
    kind: "pdf",
    title: "Oxidative Phosphorylation and ATP Synthesis",
    origin: "research_papers/nelson_2021.pdf",
    typeLabel: "PDF paper",
    abstract:
      "A review of the structural and kinetic evidence for how F1Fo ATP synthase converts the proton motive force into chemical energy.",
    saved: false,
    inReader: true,
    documentId: "doc-b",
  },
  "src-c": {
    id: "src-c",
    kind: "pdf",
    title: "Chemiosmosis in eukaryotes: comparative notes",
    origin: "research_papers/comparative_notes.pdf",
    typeLabel: "PDF paper",
    abstract:
      "Comparative notes on chemiosmotic mechanisms across eukaryotic organelles: mitochondria, chloroplasts and peroxisomal variants.",
    saved: false,
    inReader: false,
  },
  "src-t": {
    id: "src-t",
    kind: "docx",
    title: "Molecular Cell Biology — OxPhos excerpt",
    origin: "notes/textbook_excerpt.docx",
    typeLabel: "DOCX document",
    abstract:
      "Textbook excerpt on oxidative phosphorylation: the two-part story of the electron transport chain and ATP synthase, with the thermodynamics of the proton motive force.",
    saved: false,
    inReader: true,
    documentId: "doc-t",
  },
  "src-summ": {
    id: "src-summ",
    kind: "summary",
    title: "Research Summary: Chemiosmosis and ATP synthesis",
    origin: "workspace/research_summary",
    typeLabel: "Editable summary",
    abstract:
      "The session's editable research summary, fed by Paper A, Paper B and Paper C.",
    saved: false,
    inReader: true,
    documentId: "doc-summ",
  },
  /* AI Browse results */
  "ws-1": {
    id: "ws-1",
    kind: "web",
    title: "Proton gradients and ATP synthase",
    origin: "nature.com",
    url: "https://www.nature.com/articles/s41467-020-18306-7",
    typeLabel: "Research paper",
    abstract:
      "This review discusses the molecular mechanisms of proton translocation and how the proton gradient drives ATP synthesis during chemiosmosis in chloroplasts…",
    rank: 1,
    relevance: "highest",
    saved: false,
    inReader: false,
  },
  "ws-2": {
    id: "ws-2",
    kind: "web",
    title: "Structure and mechanism of chloroplast ATP synthase",
    origin: "ncbi.nlm.nih.gov",
    url: "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7123456/",
    typeLabel: "Journal article",
    abstract:
      "Structural studies reveal how the ATP synthase complex couples proton flow to ATP production, and how the proton motive force is harnessed during photosynthesis…",
    rank: 2,
    relevance: "high",
    saved: false,
    inReader: false,
  },
  "ws-3": {
    id: "ws-3",
    kind: "pdf",
    title: "The role of proton gradients in photosynthetic energy conversion",
    origin: "ieeexplore.ieee.org",
    url: "https://ieeexplore.ieee.org/document/9112233",
    typeLabel: "PDF",
    abstract:
      "This paper reviews the thermodynamics of proton gradients and the energetics of ATP synthesis in chloroplasts and cyanobacteria…",
    rank: 3,
    relevance: "good",
    saved: false,
    inReader: false,
  },
  "ws-4": {
    id: "ws-4",
    kind: "web",
    title: "ATP synthase as a rotary molecular motor: a structural review",
    origin: "semanticscholar.org",
    url: "https://www.semanticscholar.org/paper/rotary-atp-synthase",
    typeLabel: "Review",
    abstract:
      "A structural review of the rotary mechanism of F1Fo ATP synthase, including recent cryo-EM insights into proton coupling and c-ring stoichiometry…",
    rank: 4,
    relevance: "good",
    saved: false,
    inReader: false,
  },
  "ws-5": {
    id: "ws-5",
    kind: "web",
    title: "Signaling roles of the proton gradient beyond ATP synthesis",
    origin: "arxiv.org",
    url: "https://arxiv.org/abs/2304.11888",
    typeLabel: "Preprint · Zhang et al., 2023",
    abstract:
      "Argues that the chemiosmotic gradient participates in cellular signaling pathways, linking gradient dynamics to broader metabolic control…",
    rank: 5,
    relevance: "good",
    saved: false,
    inReader: false,
  },
};

/* ------------------------------------------------------------------ */
/* Documents (mock structured renderer input)                          */
/* ------------------------------------------------------------------ */

const docA: Document = {
  id: "doc-a",
  kind: "source",
  sourceId: "src-a",
  currentPage: 3,
  metadata: {
    title: "Chemiosmosis and ATP synthesis",
    author: "J. Mitchell",
    venue: "Journal of Theoretical Biology",
    year: "1961",
    format: "pdf",
    pageCount: 12,
    path: "research_papers/mitchell_1961.pdf",
  },
  highlights: [
    {
      id: "hl-a1",
      blockId: "a-p2",
      text: "The proton gradient drives ATP synthesis through ATP synthase.",
      note: "Core claim of the paper.",
      createdAt: Date.now() - 1000 * 60 * 60 * 5,
    },
  ],
  blocks: [
    { id: "a-s1", type: "heading", level: 2, segments: [{ text: "1. Introduction" }] },
    {
      id: "a-p1",
      type: "paragraph",
      segments: [
        {
          text:
            "Chemiosmosis is the process by which a proton gradient, generated across a membrane, drives the synthesis of ATP. In mitochondria and chloroplasts, the electron transport chain pumps protons from the matrix or stroma to the intermembrane space, creating an electrochemical gradient. The return flow of protons through ATP synthase provides the energy required to convert ADP and inorganic phosphate into ATP.",
        },
      ],
    },
    {
      id: "a-p2",
      type: "paragraph",
      segments: [
        {
          text: "The proton gradient drives ATP synthesis through ATP synthase.",
          highlightId: "hl-a1",
        },
      ],
    },
    {
      id: "a-p3",
      type: "paragraph",
      segments: [
        {
          text:
            "This mechanism couples redox reactions to ATP production, ensuring efficient energy transduction. The steepness of the proton gradient, measured in both pH and electrical potential, is critical for the optimal activity of ATP synthase and overall cellular energy balance.",
        },
      ],
    },
    { id: "a-s2", type: "heading", level: 2, segments: [{ text: "2. The electron transport chain" }] },
    {
      id: "a-p4",
      type: "paragraph",
      segments: [
        {
          text:
            "The electron transport chain (ETC) consists of a series of protein complexes embedded in the inner mitochondrial membrane. As electrons move from complex I and III to cytochrome c, protons are pumped from the matrix into the intermembrane space, establishing the gradient that ATP synthase will exploit.",
        },
      ],
    },
    { id: "a-s3", type: "heading", level: 2, segments: [{ text: "3. Proton gradient and membrane potential" }] },
    {
      id: "a-p5",
      type: "paragraph",
      segments: [
        {
          text:
            "The gradient formed by the chain has two components: a difference in proton concentration and an electrical potential. Together they form the proton motive force — the physical quantity that ATP synthase converts into chemical energy.",
        },
      ],
    },
    { id: "a-s4", type: "heading", level: 2, segments: [{ text: "4. ATP synthase" }] },
    {
      id: "a-p6",
      type: "paragraph",
      segments: [
        {
          text:
            "ATP synthase couples the exergonic return flow of protons to the endergonic phosphorylation of ADP. The flow of protons through the Fo unit rotates the c-ring, and this rotation drives the conformational changes in the F1 head that bind ADP and inorganic phosphate and release ATP.",
        },
      ],
    },
    { id: "a-s5", type: "heading", level: 2, segments: [{ text: "5. Regulation and efficiency" }] },
    {
      id: "a-l1",
      type: "list",
      segments: [],
      listItems: [
        [{ text: "Uncoupling proteins dissipate the gradient as heat, regulating thermal balance." }],
        [{ text: "The gradient is shared with transporters, so ATP output responds to cellular demand." }],
        [{ text: "Membrane potential feedback limits further pumping as the gradient steepens." }],
      ],
    },
    { id: "a-s6", type: "heading", level: 2, segments: [{ text: "6. Conclusion" }] },
    {
      id: "a-p7",
      type: "paragraph",
      segments: [
        {
          text:
          "Chemiosmosis provides the general framework for understanding how energy stored in a proton gradient is converted into the universal currency of the cell. Its discovery unified oxidative phosphorylation and photophosphorylation under a single physical principle.",
        },
      ],
    },
  ],
};

const docB: Document = {
  id: "doc-b",
  kind: "source",
  sourceId: "src-b",
  currentPage: 2,
  metadata: {
    title: "Oxidative Phosphorylation and ATP Synthesis",
    author: "Nelson et al.",
    venue: "Nature Reviews Molecular Cell Biology",
    year: "2021",
    format: "pdf",
    pageCount: 18,
    path: "research_papers/nelson_2021.pdf",
  },
  highlights: [],
  blocks: [
    { id: "b-s1", type: "heading", level: 2, segments: [{ text: "Abstract" }] },
    {
      id: "b-p1",
      type: "paragraph",
      segments: [
        {
          text:
            "Oxidative phosphorylation couples electron transport to ATP synthesis through the proton motive force. This review summarizes recent structural and kinetic evidence for how the F1Fo ATP synthase complex converts the electrochemical gradient of protons into the chemical energy of ATP.",
        },
      ],
    },
    { id: "b-s2", type: "heading", level: 2, segments: [{ text: "The proton motive force" }] },
    {
      id: "b-p2",
      type: "paragraph",
      segments: [
        {
          text:
            "The proton motive force integrates the membrane potential and the transmembrane pH gradient. Both components contribute to the free energy available to the synthase, and their relative weighting varies across organisms and metabolic states.",
        },
      ],
    },
    { id: "b-s3", type: "heading", level: 2, segments: [{ text: "Structure of ATP synthase" }] },
    {
      id: "b-p3",
      type: "paragraph",
      segments: [
        {
          text:
            "Cryo-EM structures show the Fo c-ring rotating within a stator framework, with the gamma-subunit transmitting torque to the catalytic heads. The number of c-subunits determines the number of protons required per ATP synthesized.",
        },
      ],
    },
    { id: "b-s4", type: "heading", level: 2, segments: [{ text: "Regulation and uncoupling" }] },
    {
      id: "b-l1",
      type: "list",
      segments: [],
      listItems: [
        [{ text: "Uncoupling proteins dissipate the proton motive force to regulate thermogenesis." }],
        [{ text: "Rotational drag from ATP hydrolysis can feed protons back into the matrix." }],
        [{ text: "The enzyme operates reversibly when the gradient falls below ~130 mV." }],
      ],
    },
  ],
};

const docC: Document = {
  id: "doc-c",
  kind: "source",
  sourceId: "src-c",
  currentPage: 1,
  metadata: {
    title: "Chemiosmosis in eukaryotes: comparative notes",
    author: "Session notes",
    venue: "Local document",
    year: "2023",
    format: "pdf",
    pageCount: 6,
    path: "research_papers/comparative_notes.pdf",
  },
  highlights: [],
  blocks: [
    { id: "c-s1", type: "heading", level: 2, segments: [{ text: "Scope" }] },
    {
      id: "c-p1",
      type: "paragraph",
      segments: [
        {
          text:
            "These notes compare chemiosmotic mechanisms across eukaryotic organelles: mitochondria, chloroplasts, and peroxisomal variants.",
        },
      ],
    },
    { id: "c-s2", type: "heading", level: 2, segments: [{ text: "Cross-organellar comparison" }] },
    {
      id: "c-p2",
      type: "paragraph",
      segments: [
        {
          text:
            "The direction of proton movement reverses between mitochondria and chloroplasts, but the underlying coupling logic — a gradient powering a rotary synthase — is conserved.",
        },
      ],
    },
    {
      id: "c-l1",
      type: "list",
      segments: [],
      listItems: [
        [{ text: "Mitochondria: the matrix is the negative compartment." }],
        [{ text: "Chloroplasts: the stroma is the negative compartment." }],
        [{ text: "Both: one gradient, one synthase family, one currency (ATP)." }],
      ],
    },
  ],
};

const docT: Document = {
  id: "doc-t",
  kind: "source",
  sourceId: "src-t",
  currentPage: 1,
  metadata: {
    title: "Molecular Cell Biology — OxPhos excerpt",
    author: "Textbook",
    venue: "Chapter 9 excerpt",
    year: "2017",
    format: "docx",
    pageCount: 4,
    path: "notes/textbook_excerpt.docx",
  },
  highlights: [],
  blocks: [
    { id: "t-s1", type: "heading", level: 2, segments: [{ text: "Chapter 9 — Oxidative phosphorylation (excerpt)" }] },
    {
      id: "t-p1",
      type: "paragraph",
      segments: [
        {
          text:
            "Textbooks traditionally present oxidative phosphorylation in two linked parts: the electron transport chain, which builds the proton gradient, and ATP synthase, which spends it.",
        },
      ],
    },
    { id: "t-s2", type: "heading", level: 2, segments: [{ text: "Key ideas" }] },
    {
      id: "t-l1",
      type: "list",
      segments: [],
      listItems: [
        [{ text: "Energy from redox reactions is stored temporarily as a gradient." }],
        [{ text: "The gradient, not a high-energy intermediate, is the carrier." }],
        [{ text: "ATP synthase is a molecular machine that transduces gradient energy." }],
      ],
    },
    {
      id: "t-p2",
      type: "paragraph",
      segments: [
        {
          text:
            "Modern treatments emphasize the thermodynamic coupling: the free energy of the proton motive force sets the upper limit on what phosphorylation can extract from the gradient.",
        },
      ],
    },
  ],
};

/** The editable session summary. Blocks carry pending AI changes. */
const docSumm: Document = {
  id: "doc-summ",
  kind: "summary",
  sourceId: "src-summ",
  sourceIds: ["src-a", "src-b", "src-c"],
  metadata: {
    title: "Research Summary: Chemiosmosis and ATP synthesis",
    format: "summary",
  },
  highlights: [],
  blocks: [
    { id: "s-h1", type: "heading", level: 1, segments: [{ text: "Research Summary: Chemiosmosis and ATP synthesis" }] },
    { id: "s-s1", type: "heading", level: 2, segments: [{ text: "1. Introduction" }] },
    {
      id: "s-p1",
      type: "paragraph",
      segments: [
        {
          text:
            "Chemiosmosis is the process by which cells harness the energy stored in electrochemical gradients to drive ATP synthesis. First described by Peter Mitchell in 1961, the theory explains how the movement of protons across a membrane is coupled to the production of ATP by ATP synthase (Mitchell, 1961). This mechanism is central to cellular respiration and photosynthesis, and it underpins the energetic efficiency of life. (Mitchell, 1961; Nelson & Cox, 2017)",
        },
      ],
    },
    {
      id: "s-ai1",
      type: "paragraph",
      changeId: "chg-1",
      segments: [
        {
          text:
            "Recent research suggests that the chemiosmotic mechanism also plays a role in regulating cellular signaling, linking the proton gradient to broader metabolic control beyond ATP production. (Zhang et al., 2023)",
        },
      ],
    },
    { id: "s-s2", type: "heading", level: 2, segments: [{ text: "2. The Proton Gradient" }] },
    {
      id: "s-p2",
      type: "paragraph",
      segments: [
        {
          text:
            "The electron transport chain pumps protons from the mitochondrial matrix to the intermembrane space, creating a gradient of both concentration and electrical potential. (Nelson & Cox, 2017)",
        },
      ],
    },
    { id: "s-s3", type: "heading", level: 2, segments: [{ text: "3. ATP Synthase and ATP Production" }] },
    {
      id: "s-p3",
      type: "paragraph",
      segments: [
        {
          text:
            "ATP synthase uses the flow of protons to drive the phosphorylation of ADP to ATP. The enzyme rotates as protons move through its Fo subunit, coupling the gradient to mechanical motion and chemical energy conversion. (Abrahams et al., 1994)",
        },
      ],
    },
  ],
};

export const documents: Record<string, Document> = {
  "doc-a": docA,
  "doc-b": docB,
  "doc-c": docC,
  "doc-t": docT,
  "doc-summ": docSumm,
};

/* ------------------------------------------------------------------ */
/* Initial AI changes (proposal system demo)                           */
/* ------------------------------------------------------------------ */

const MIN = 60_000;

const changes: Record<string, DocumentChange> = {
  "chg-1": {
    id: "chg-1",
    documentId: "doc-summ",
    type: "insert",
    blockId: "s-ai1",
    oldContent: "",
    newContent:
      "Recent research suggests that the chemiosmotic mechanism also plays a role in regulating cellular signaling, linking the proton gradient to broader metabolic control beyond ATP production. (Zhang et al., 2023)",
    sourceId: "ws-5",
    activityId: "act-2",
    status: "pending",
    createdAt: Date.now() - 11 * MIN,
  },
  "chg-2": {
    id: "chg-2",
    documentId: "doc-summ",
    type: "modify",
    blockId: "s-p2",
    oldContent:
      "The electron transport chain pumps protons from the mitochondrial matrix to the intermembrane space, creating a gradient of both concentration and electrical potential. (Nelson & Cox, 2017)",
    newContent:
      "The electron transport chain pumps protons from the mitochondrial matrix to the intermembrane space, creating a gradient of both concentration and electrical potential. This gradient stores energy that is later released as protons flow back through ATP synthase. (Nelson & Cox, 2017)",
    highlightFragment:
      "This gradient stores energy that is later released as protons flow back through ATP synthase.",
    sourceId: "src-b",
    activityId: "act-3",
    status: "pending",
    createdAt: Date.now() - 9 * MIN,
  },
};

const aiActivities: AIActivity[] = [
  {
    id: "act-3",
    operation: "AI_REWRITE",
    status: "completed",
    message: "Proposed a sentence addition to “The Proton Gradient”",
    documentId: "doc-summ",
    sourceId: "src-b",
    changeIds: ["chg-2"],
    startedAt: Date.now() - 9 * MIN - 40_000,
    finishedAt: Date.now() - 9 * MIN,
  },
  {
    id: "act-2",
    operation: "AI_MERGE",
    status: "completed",
    message: "Proposed a new paragraph from arXiv preprint (Zhang et al., 2023)",
    documentId: "doc-summ",
    sourceId: "ws-5",
    changeIds: ["chg-1"],
    startedAt: Date.now() - 11 * MIN - 40_000,
    finishedAt: Date.now() - 11 * MIN,
  },
  {
    id: "act-1",
    operation: "AI_SEARCH",
    status: "completed",
    message: "Ranked 5 sources for “mechanism of ATP production during chemiosmosis”",
    changeIds: [],
    startedAt: Date.now() - 14 * MIN - 3_400,
    finishedAt: Date.now() - 14 * MIN,
  },
];

/* ------------------------------------------------------------------ */
/* Browser + reader sessions                                           */
/* ------------------------------------------------------------------ */

const tab = (id: string, title: string, url: string): BrowserTab => ({
  id,
  title,
  nav: { currentUrl: url, history: [url], index: 0 },
});

const browserSessions: BrowserSession[] = [
  {
    id: "sess-1",
    title: "Photosynthesis — Chemiosmosis",
    tabIds: ["t-search", "t-a", "t-b", "t-c"],
    activeTabId: "t-b",
  },
  { id: "sess-2", title: "CRISPR gene editing", tabIds: ["t-n1"], activeTabId: "t-n1" },
  { id: "sess-3", title: "Climate change impacts", tabIds: ["t-n2"], activeTabId: "t-n2" },
];

const browserTabs: Record<string, BrowserTab> = {
  "t-search": tab("t-search", "Search results", "lumen://search?q=chemiosmosis%20ATP%20synthesis"),
  "t-a": tab("t-a", "Paper A", "https://www.nature.com/articles/s41467-020-16742-1"),
  "t-b": tab("t-b", "Paper B", "https://www.nature.com/articles/s41467-020-18306-7"),
  "t-c": tab("t-c", "Paper C", "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7123456/"),
  "t-n1": tab("t-n1", "New tab", "lumen://newtab"),
  "t-n2": tab("t-n2", "New tab", "lumen://newtab"),
};

/* ------------------------------------------------------------------ */
/* File tree (mock of the Go filesystem service)                       */
/* ------------------------------------------------------------------ */

export const fileTreeMock: FileTreeNode = {
  id: "ft-root",
  label: "research_workspace",
  kind: "folder",
  children: [
    {
      id: "ft-papers",
      label: "research_papers",
      kind: "folder",
      children: [
        { id: "ft-mitchell", label: "mitchell_1961.pdf", kind: "file", ext: "pdf", documentId: "doc-a" },
        { id: "ft-nelson", label: "nelson_2021.pdf", kind: "file", ext: "pdf", documentId: "doc-b" },
        { id: "ft-comparative", label: "comparative_notes.pdf", kind: "file", ext: "pdf", documentId: "doc-c" },
        { id: "ft-figures", label: "figures", kind: "folder" },
        { id: "ft-suppl", label: "supplementary.pdf", kind: "file", ext: "pdf" },
      ],
    },
    {
      id: "ft-notes",
      label: "notes",
      kind: "folder",
      children: [
        { id: "ft-textbook", label: "textbook_excerpt.docx", kind: "file", ext: "docx", documentId: "doc-t" },
        { id: "ft-field", label: "field_notes.docx", kind: "file", ext: "docx" },
      ],
    },
  ],
};

/* ------------------------------------------------------------------ */
/* Document factory — used by "Send to Reader" / "Open document"       */
/* ------------------------------------------------------------------ */

export function makeDocumentFromSource(sourceId: string, source: Source, docId: string): Document {
  const isWeb = source.kind === "web" || source.kind === "html";
  return {
    id: docId,
    kind: "source",
    sourceId,
    currentPage: 1,
    metadata: {
      title: source.title,
      author: source.origin,
      venue: source.typeLabel,
      format: source.kind === "pdf" ? "pdf" : source.kind === "docx" ? "docx" : isWeb ? "html" : "text",
      pageCount: source.kind === "pdf" ? 8 : 3,
      path: source.url ? undefined : source.origin,
    },
    highlights: [],
    blocks: [
      { id: `${docId}-s1`, type: "heading", level: 2, segments: [{ text: isWeb ? "About this article" : "Overview" }] },
      { id: `${docId}-p1`, type: "paragraph", segments: [{ text: source.abstract }] },
      { id: `${docId}-s2`, type: "heading", level: 2, segments: [{ text: "Why this is in your session" }] },
      {
        id: `${docId}-p2`,
        type: "paragraph",
        segments: [
          {
            text: isWeb
              ? "Opened from an AI Browse result. Rendered with the mock structured renderer — the real HTML/PDF pipeline is a documented integration point (docs/document-rendering.md)."
              : "Opened from the workspace file tree. Rendered with the mock structured renderer — the real DOCX/PDF pipeline is a documented integration point (docs/document-rendering.md).",
          },
        ],
      },
    ],
  };
}

/* ------------------------------------------------------------------ */
/* Initial app state                                                   */
/* ------------------------------------------------------------------ */

export function createInitialState(): AppState {
  return {
    mode: "reader",
    browser: {
      sessions: browserSessions,
      activeSessionId: "sess-1",
      tabs: browserTabs,
      ui: { sidebarOpen: true, aiPanelOpen: true, aiPanelWidth: 360 },
    },
    reader: {
      session: { id: "rs-1", tabIds: ["rt-a", "rt-b", "rt-t", "rt-summ"], activeTabId: "rt-a" },
      tabs: {
        "rt-a": { id: "rt-a", documentId: "doc-a", label: "Paper A" },
        "rt-b": { id: "rt-b", documentId: "doc-b", label: "Paper B" },
        "rt-t": { id: "rt-t", documentId: "doc-t", label: "Textbook" },
        "rt-summ": { id: "rt-summ", documentId: "doc-summ", label: "Research Summary" },
      },
      ui: {
        railOpen: true,
        sidebarOpen: true,
        railView: "documents",
        aiPanelOpen: true,
        aiPanelWidth: 330,
        companion: {
          documentId: "doc-a",
          passage: "The proton gradient drives ATP synthesis through ATP synthase.",
          explanation:
            "The proton gradient creates a flow of H+ ions back into the mitochondrial matrix (or stroma) through ATP synthase. This flow provides the energy for ATP synthase to convert ADP and inorganic phosphate into ATP, a process called chemiosmosis.",
          sourceLabel: "Nelson et al. (2021), Nature Reviews Molecular Cell Biology",
        },
      },
    },
    sources,
    documents,
    changes,
    aiActivities,
    browse: {
      status: "done",
      query: "mechanism of ATP production during chemiosmosis",
      phase: 5,
      sourceIds: ["ws-1", "ws-2", "ws-3", "ws-4", "ws-5"],
    },
    selection: null,
    toast: null,
    settingsOpen: false,
    previewSourceId: null,
  };
}
