// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExtractDocument(arg1) {
  return window['go']['frontend']['App']['ExtractDocument'](arg1);
}

export function GetSources() {
  return window['go']['frontend']['App']['GetSources']();
}

export function Greet(arg1) {
  return window['go']['frontend']['App']['Greet'](arg1);
}

export function ListWorkspace() {
  return window['go']['frontend']['App']['ListWorkspace']();
}

export function SaveWorkspace() {
  return window['go']['frontend']['App']['SaveWorkspace']();
}

export function ShowContainingFolder(arg1) {
  return window['go']['frontend']['App']['ShowContainingFolder'](arg1);
}

export function StorageEngine() {
  return window['go']['frontend']['App']['StorageEngine']();
}

export function StreamAIRequest(arg1) {
  return window['go']['frontend']['App']['StreamAIRequest'](arg1);
}
