// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AppendChatMessage(arg1) {
  return window['go']['frontend']['App']['AppendChatMessage'](arg1);
}

export function LibraryRoot() {
  return window['go']['frontend']['App']['LibraryRoot']();
}

export function ListDocuments(arg1) {
  return window['go']['frontend']['App']['ListDocuments'](arg1);
}

export function ListLibraryTree() {
  return window['go']['frontend']['App']['ListLibraryTree']();
}

export function ListMessages(arg1) {
  return window['go']['frontend']['App']['ListMessages'](arg1);
}

export function ListPendingChanges(arg1) {
  return window['go']['frontend']['App']['ListPendingChanges'](arg1);
}

export function ListThreads(arg1) {
  return window['go']['frontend']['App']['ListThreads'](arg1);
}

export function ListTree() {
  return window['go']['frontend']['App']['ListTree']();
}

export function LoadDocument(arg1) {
  return window['go']['frontend']['App']['LoadDocument'](arg1);
}

export function LoadPrimarySummary(arg1) {
  return window['go']['frontend']['App']['LoadPrimarySummary'](arg1);
}

export function LoadThread(arg1) {
  return window['go']['frontend']['App']['LoadThread'](arg1);
}

export function OpenFile(arg1) {
  return window['go']['frontend']['App']['OpenFile'](arg1);
}

export function ResolvePath(arg1) {
  return window['go']['frontend']['App']['ResolvePath'](arg1);
}

export function RunAI(arg1) {
  return window['go']['frontend']['App']['RunAI'](arg1);
}

export function SaveChange(arg1) {
  return window['go']['frontend']['App']['SaveChange'](arg1);
}

export function SaveDocument(arg1) {
  return window['go']['frontend']['App']['SaveDocument'](arg1);
}

export function SaveThread(arg1) {
  return window['go']['frontend']['App']['SaveThread'](arg1);
}

export function SelectFolder() {
  return window['go']['frontend']['App']['SelectFolder']();
}

export function SetLibraryRoot(arg1) {
  return window['go']['frontend']['App']['SetLibraryRoot'](arg1);
}

export function SetPrimarySummary(arg1) {
  return window['go']['frontend']['App']['SetPrimarySummary'](arg1);
}

export function ShowContainingFolder(arg1) {
  return window['go']['frontend']['App']['ShowContainingFolder'](arg1);
}

export function StorageEngine() {
  return window['go']['frontend']['App']['StorageEngine']();
}

export function StreamAIRequest(arg1) {
  return window['go']['frontend']['App']['StreamAIRequest'](arg1);
}

export function WorkspaceID() {
  return window['go']['frontend']['App']['WorkspaceID']();
}

export function WriteSummaryDOCX(arg1, arg2) {
  return window['go']['frontend']['App']['WriteSummaryDOCX'](arg1, arg2);
}
