// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function ExtractDocument(arg1:models.Source):Promise<string>;

export function GetSources():Promise<Array<models.Source>>;

export function Greet(arg1:string):Promise<string>;

export function ListWorkspace():Promise<Array<models.FileTreeNode>>;

export function SaveWorkspace():Promise<void>;

export function ShowContainingFolder(arg1:string):Promise<string>;

export function StorageEngine():Promise<string>;

export function StreamAIRequest(arg1:models.AIRequest):Promise<void>;
