// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {services} from '../models';
import {models} from '../models';

export function AppendChatMessage(arg1:services.ChatMessageRecord):Promise<void>;

export function LibraryRoot():Promise<string>;

export function ListDocuments(arg1:string):Promise<Array<services.DocumentRecord>>;

export function ListLibraryTree():Promise<models.FileTreeNode>;

export function ListMessages(arg1:string):Promise<Array<services.ChatMessageRecord>>;

export function ListPendingChanges(arg1:string):Promise<Array<services.ChangeRecord>>;

export function ListThreads(arg1:string):Promise<Array<services.ChatThreadRecord>>;

export function ListTree():Promise<Array<models.FileTreeNode>>;

export function LoadDocument(arg1:string):Promise<services.DocumentRecord>;

export function LoadPrimarySummary(arg1:string):Promise<services.DocumentRecord>;

export function LoadThread(arg1:string):Promise<services.ChatThreadRecord>;

export function OpenFile(arg1:string):Promise<models.OpenedDocument>;

export function ResolvePath(arg1:string):Promise<string>;

export function RunAI(arg1:models.AIRequest):Promise<void>;

export function SaveChange(arg1:services.ChangeRecord):Promise<void>;

export function SaveDocument(arg1:services.DocumentRecord):Promise<void>;

export function SaveThread(arg1:services.ChatThreadRecord):Promise<void>;

export function SelectFolder():Promise<string>;

export function SetLibraryRoot(arg1:string):Promise<void>;

export function SetPrimarySummary(arg1:string):Promise<void>;

export function ShowContainingFolder(arg1:string):Promise<string>;

export function StorageEngine():Promise<string>;

export function StreamAIRequest(arg1:models.AIRequest):Promise<void>;

export function WorkspaceID():Promise<string>;

export function WriteSummaryDOCX(arg1:string,arg2:string):Promise<string>;
